#!/usr/bin/env bash

#  Get the full path to the spec file
SPECFILE=$(dirname "$(realpath "$0")")/tsmuxer.spec

#  Parse the package name out of the spec file
NAME=$(sed -n 's/^Name:[[:space:]]*//p' "$SPECFILE")

#  Clone the source from git into a temp file
TMPDIR=$(mktemp -d)
cd $TMPDIR
git clone https://github.com/justdan96/tsMuxer.git

#  Get the program version number from the code
cd tsMuxer
VERSION=$(grep "APP_VERSION =" tsMuxer/main.cpp | sed 's/[^"]*"\([^"]*\)".*/\1/')

#  Modify the spec file to set the current version number
sed -i "s/^Version:.*/Version:\t${VERSION}/" "$SPECFILE"

#  Build a tar.gz archive of the source code and put it in our SOURCES dir
git archive --format=tar.gz --prefix=${NAME}-${VERSION}/ --output=${HOME}/rpmbuild/SOURCES/${NAME}-${VERSION}.tar.gz master

#  Put the desktop file into the archive file
wget -O $TMPDIR/tsMuxerGUI.desktop "https://github.com/dlk3/tsmuxer-spec/blob/master/tsMuxerGUI.desktop"
tar --append -f ${HOME}/rpmbuild/SOURCES/${NAME}-${VERSION}.tar.gz --transform "s|$TMPDIR|${NAME}-${VERSION}|" $TMPDIR/tsMuxerGUI.desktop

#  Remove the temporary directory
rm -fr $TMPDIR

#  Build the packages
rpmbuild -ba "$SPECFILE"

